"""create catalog tables

Revision ID: 1a202060566b
Revises: cff5f80e0d74
Create Date: 2026-05-27 06:40:49.467736+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1a202060566b"
down_revision: str | Sequence[str] | None = "cff5f80e0d74"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categories")),
        sa.UniqueConstraint("name", name=op.f("uq_categories_name")),
    )
    op.create_index("idx_categories_is_active", "categories", ["is_active"], unique=False)
    op.create_table(
        "product_types",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_types")),
        sa.UniqueConstraint("name", name=op.f("uq_product_types_name")),
    )
    op.create_table(
        "products",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("image_url", sa.String(length=500), nullable=True),
        sa.Column("category_id", sa.UUID(), nullable=False),
        sa.Column("product_type_id", sa.UUID(), nullable=False),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), server_default=sa.text("'EUR'"), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("price > 0", name=op.f("ck_products_price_positive")),
        sa.ForeignKeyConstraint(
            ["category_id"], ["categories.id"], name=op.f("fk_products_category_id_categories")
        ),
        sa.ForeignKeyConstraint(
            ["product_type_id"],
            ["product_types.id"],
            name=op.f("fk_products_product_type_id_product_types"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
    )
    op.create_index("idx_products_category_id", "products", ["category_id"], unique=False)
    op.create_index("idx_products_is_active", "products", ["is_active"], unique=False)
    op.create_index("idx_products_product_type_id", "products", ["product_type_id"], unique=False)
    op.create_table(
        "product_accessories",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("accessory_type", sa.String(length=50), nullable=False),
        sa.Column("material", sa.String(length=100), nullable=False),
        sa.Column("other_options", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "accessory_type IN "
            "('filter', 'tamper', 'scale', 'pitcher', 'thermometer', 'knockbox', 'other')",
            name=op.f("ck_product_accessories_accessory_type"),
        ),
        sa.ForeignKeyConstraint(
            ["id"],
            ["products.id"],
            name=op.f("fk_product_accessories_id_products"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_accessories")),
    )
    op.create_table(
        "product_coffee",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("region", sa.String(length=100), nullable=False),
        sa.Column("roast_level", sa.String(length=20), nullable=False),
        sa.Column("acidity", sa.SmallInteger(), nullable=False),
        sa.Column("body", sa.SmallInteger(), nullable=False),
        sa.Column("sweetness", sa.SmallInteger(), nullable=False),
        sa.Column("processing", sa.String(length=50), nullable=False),
        sa.Column("altitude", sa.Integer(), nullable=True),
        sa.Column("flavor_notes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "processing IN ('washed', 'natural', 'anaerobic', 'honey')",
            name=op.f("ck_product_coffee_processing"),
        ),
        sa.CheckConstraint(
            "roast_level IN ('light', 'medium', 'dark')", name=op.f("ck_product_coffee_roast_level")
        ),
        sa.CheckConstraint("acidity BETWEEN 1 AND 5", name=op.f("ck_product_coffee_acidity_scale")),
        sa.CheckConstraint("body BETWEEN 1 AND 5", name=op.f("ck_product_coffee_body_scale")),
        sa.CheckConstraint(
            "sweetness BETWEEN 1 AND 5", name=op.f("ck_product_coffee_sweetness_scale")
        ),
        sa.ForeignKeyConstraint(
            ["id"], ["products.id"], name=op.f("fk_product_coffee_id_products"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_coffee")),
    )
    op.create_index("idx_product_coffee_acidity", "product_coffee", ["acidity"], unique=False)
    op.create_index("idx_product_coffee_altitude", "product_coffee", ["altitude"], unique=False)
    op.create_index("idx_product_coffee_body", "product_coffee", ["body"], unique=False)
    op.create_index(
        "idx_product_coffee_flavor_keys",
        "product_coffee",
        [sa.literal_column("(flavor_notes -> 'keys')")],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index("idx_product_coffee_processing", "product_coffee", ["processing"], unique=False)
    op.create_index("idx_product_coffee_region", "product_coffee", ["region"], unique=False)
    op.create_index(
        "idx_product_coffee_roast_level", "product_coffee", ["roast_level"], unique=False
    )
    op.create_index("idx_product_coffee_sweetness", "product_coffee", ["sweetness"], unique=False)
    op.create_table(
        "product_compatibility",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("accessory_product_id", sa.UUID(), nullable=False),
        sa.Column("compatible_product_id", sa.UUID(), nullable=False),
        sa.Column("compatibility_notes", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "accessory_product_id != compatible_product_id",
            name=op.f("ck_product_compatibility_not_self_compatible"),
        ),
        sa.ForeignKeyConstraint(
            ["accessory_product_id"],
            ["products.id"],
            name=op.f("fk_product_compatibility_accessory_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["compatible_product_id"],
            ["products.id"],
            name=op.f("fk_product_compatibility_compatible_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_compatibility")),
        sa.UniqueConstraint(
            "accessory_product_id",
            "compatible_product_id",
            name=op.f("uq_product_compatibility_accessory_product_id"),
        ),
    )
    op.create_index(
        "idx_productcompat_compatible_id",
        "product_compatibility",
        ["compatible_product_id"],
        unique=False,
    )
    op.create_table(
        "product_consumables",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("consumable_type", sa.String(length=50), nullable=False),
        sa.Column("quantity_per_pack", sa.Integer(), nullable=False),
        sa.Column("unit_description", sa.String(length=50), nullable=False),
        sa.Column("material", sa.String(length=100), nullable=True),
        sa.Column("other_options", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("expiry_months", sa.Integer(), nullable=True),
        sa.Column("storage_conditions", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "consumable_type IN ('filter', 'pods', 'cleaning', 'water', 'other')",
            name=op.f("ck_product_consumables_consumable_type"),
        ),
        sa.CheckConstraint(
            "expiry_months IS NULL OR expiry_months > 0",
            name=op.f("ck_product_consumables_expiry_positive"),
        ),
        sa.CheckConstraint(
            "quantity_per_pack > 0", name=op.f("ck_product_consumables_quantity_positive")
        ),
        sa.ForeignKeyConstraint(
            ["id"],
            ["products.id"],
            name=op.f("fk_product_consumables_id_products"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_consumables")),
    )
    op.create_table(
        "product_equipment",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("equipment_type", sa.String(length=50), nullable=False),
        sa.Column("power_watts", sa.Integer(), nullable=True),
        sa.Column("warranty_months", sa.Integer(), nullable=True),
        sa.Column("width_cm", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("height_cm", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("depth_cm", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("weight_kg", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("material", sa.String(length=100), nullable=True),
        sa.Column("other_options", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "equipment_type IN ('machine', 'grinder', 'brewer', 'scale', 'other')",
            name=op.f("ck_product_equipment_equipment_type"),
        ),
        sa.CheckConstraint(
            "depth_cm IS NULL OR depth_cm > 0", name=op.f("ck_product_equipment_depth_positive")
        ),
        sa.CheckConstraint(
            "height_cm IS NULL OR height_cm > 0", name=op.f("ck_product_equipment_height_positive")
        ),
        sa.CheckConstraint(
            "power_watts IS NULL OR power_watts > 0",
            name=op.f("ck_product_equipment_power_positive"),
        ),
        sa.CheckConstraint(
            "warranty_months IS NULL OR warranty_months >= 0",
            name=op.f("ck_product_equipment_warranty_non_negative"),
        ),
        sa.CheckConstraint(
            "width_cm IS NULL OR width_cm > 0", name=op.f("ck_product_equipment_width_positive")
        ),
        sa.ForeignKeyConstraint(
            ["id"],
            ["products.id"],
            name=op.f("fk_product_equipment_id_products"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_equipment")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("product_equipment")
    op.drop_table("product_consumables")
    op.drop_index("idx_productcompat_compatible_id", table_name="product_compatibility")
    op.drop_table("product_compatibility")
    op.drop_index("idx_product_coffee_sweetness", table_name="product_coffee")
    op.drop_index("idx_product_coffee_roast_level", table_name="product_coffee")
    op.drop_index("idx_product_coffee_region", table_name="product_coffee")
    op.drop_index("idx_product_coffee_processing", table_name="product_coffee")
    op.drop_index(
        "idx_product_coffee_flavor_keys", table_name="product_coffee", postgresql_using="gin"
    )
    op.drop_index("idx_product_coffee_body", table_name="product_coffee")
    op.drop_index("idx_product_coffee_altitude", table_name="product_coffee")
    op.drop_index("idx_product_coffee_acidity", table_name="product_coffee")
    op.drop_table("product_coffee")
    op.drop_table("product_accessories")
    op.drop_index("idx_products_product_type_id", table_name="products")
    op.drop_index("idx_products_is_active", table_name="products")
    op.drop_index("idx_products_category_id", table_name="products")
    op.drop_table("products")
    op.drop_table("product_types")
    op.drop_index("idx_categories_is_active", table_name="categories")
    op.drop_table("categories")
    # ### end Alembic commands ###
