"""create subscription tables

Revision ID: ff2257ab755e
Revises: 03c347c01bed
Create Date: 2026-05-28 19:00:29.331725+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ff2257ab755e"
down_revision: str | Sequence[str] | None = "03c347c01bed"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscriptions",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "status", sa.String(length=20), server_default=sa.text("'pending'"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'active', 'paused', 'cancelled', 'completed')",
            name=op.f("ck_subscriptions_status"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_subscriptions_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscriptions")),
    )
    op.create_index("idx_subscriptions_status", "subscriptions", ["status"], unique=False)
    op.create_index("idx_subscriptions_user_id", "subscriptions", ["user_id"], unique=False)
    op.create_table(
        "subscription_delivery_info",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("subscription_id", sa.UUID(), nullable=False),
        sa.Column("recipient_name", sa.String(length=255), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("address", sa.Text(), nullable=False),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("postal_code", sa.String(length=20), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscriptions.id"],
            name=op.f("fk_subscription_delivery_info_subscription_id_subscriptions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscription_delivery_info")),
        sa.UniqueConstraint(
            "subscription_id", name=op.f("uq_subscription_delivery_info_subscription_id")
        ),
    )
    op.create_index(
        "idx_subscription_delivery_info_city", "subscription_delivery_info", ["city"], unique=False
    )
    op.create_table(
        "subscription_events",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("subscription_id", sa.UUID(), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=True),
        sa.Column("scheduled_date", sa.Date(), nullable=False),
        sa.Column("price_per_delivery", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), server_default=sa.text("'EUR'"), nullable=False),
        sa.Column(
            "status", sa.String(length=20), server_default=sa.text("'pending'"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'ready', 'paused', 'completed', 'cancelled')",
            name=op.f("ck_subscription_events_status"),
        ),
        sa.CheckConstraint(
            "price_per_delivery > 0", name=op.f("ck_subscription_events_price_positive")
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_subscription_events_order_id_orders"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscriptions.id"],
            name=op.f("fk_subscription_events_subscription_id_subscriptions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscription_events")),
        sa.UniqueConstraint(
            "subscription_id", "scheduled_date", name=op.f("uq_subscription_events_subscription_id")
        ),
    )
    op.create_index(
        "idx_subscription_events_order_id", "subscription_events", ["order_id"], unique=False
    )
    op.create_index(
        "idx_subscription_events_scheduled_date",
        "subscription_events",
        ["scheduled_date"],
        unique=False,
    )
    op.create_index(
        "idx_subscription_events_status", "subscription_events", ["status"], unique=False
    )
    op.create_index(
        "idx_subscription_events_subscription_id",
        "subscription_events",
        ["subscription_id"],
        unique=False,
    )
    op.create_table(
        "subscription_payments",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("subscription_event_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("payment_method", sa.String(length=30), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("provider_transaction_id", sa.String(length=255), nullable=True),
        sa.Column(
            "status", sa.String(length=20), server_default=sa.text("'pending'"), nullable=False
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'completed', 'failed', 'refunded')",
            name=op.f("ck_subscription_payments_status"),
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_subscription_payments_amount_positive")),
        sa.ForeignKeyConstraint(
            ["subscription_event_id"],
            ["subscription_events.id"],
            name=op.f("fk_subscription_payments_subscription_event_id_subscription_events"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_subscription_payments_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscription_payments")),
    )
    op.create_index(
        "idx_subscription_payments_event_id",
        "subscription_payments",
        ["subscription_event_id"],
        unique=False,
    )
    op.create_index(
        "idx_subscription_payments_provider_txn",
        "subscription_payments",
        ["provider_transaction_id"],
        unique=False,
    )
    op.create_index(
        "idx_subscription_payments_user_id", "subscription_payments", ["user_id"], unique=False
    )
    op.create_table(
        "subscription_products",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("subscription_event_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("product_name", sa.String(length=255), nullable=False),
        sa.Column("product_price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "product_price > 0", name=op.f("ck_subscription_products_price_positive")
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_subscription_products_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["subscription_event_id"],
            ["subscription_events.id"],
            name=op.f("fk_subscription_products_subscription_event_id_subscription_events"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscription_products")),
        sa.UniqueConstraint(
            "subscription_event_id", name=op.f("uq_subscription_products_subscription_event_id")
        ),
    )
    op.create_index(
        "idx_subscription_products_product_id",
        "subscription_products",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        "idx_subscription_products_subscription_event_id",
        "subscription_products",
        ["subscription_event_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_subscription_products_subscription_event_id", table_name="subscription_products"
    )
    op.drop_index("idx_subscription_products_product_id", table_name="subscription_products")
    op.drop_table("subscription_products")
    op.drop_index("idx_subscription_payments_user_id", table_name="subscription_payments")
    op.drop_index("idx_subscription_payments_provider_txn", table_name="subscription_payments")
    op.drop_index("idx_subscription_payments_event_id", table_name="subscription_payments")
    op.drop_table("subscription_payments")
    op.drop_index("idx_subscription_events_subscription_id", table_name="subscription_events")
    op.drop_index("idx_subscription_events_status", table_name="subscription_events")
    op.drop_index("idx_subscription_events_scheduled_date", table_name="subscription_events")
    op.drop_index("idx_subscription_events_order_id", table_name="subscription_events")
    op.drop_table("subscription_events")
    op.drop_index("idx_subscription_delivery_info_city", table_name="subscription_delivery_info")
    op.drop_table("subscription_delivery_info")
    op.drop_index("idx_subscriptions_user_id", table_name="subscriptions")
    op.drop_index("idx_subscriptions_status", table_name="subscriptions")
    op.drop_table("subscriptions")
    # ### end Alembic commands ###
