"""create orders and points tables

Revision ID: 03c347c01bed
Revises: e38361f22261
Create Date: 2026-05-27 08:33:30.927653+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "03c347c01bed"
down_revision: str | Sequence[str] | None = "e38361f22261"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "points",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("address", sa.Text(), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("hours", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("contacts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "type IN ('coffeeshop', 'warehouse', 'roastery')", name=op.f("ck_points_type")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_points")),
    )
    op.create_index("idx_points_is_active", "points", ["is_active"], unique=False)
    op.create_index("idx_points_name", "points", ["name"], unique=False)
    op.create_index("idx_points_type", "points", ["type"], unique=False)
    op.create_table(
        "orders",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("order_type", sa.String(length=20), nullable=False),
        sa.Column("total_price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), server_default=sa.text("'EUR'"), nullable=False),
        sa.Column(
            "status", sa.String(length=30), server_default=sa.text("'created'"), nullable=False
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "order_type IN ('pickup', 'delivery')", name=op.f("ck_orders_order_type")
        ),
        sa.CheckConstraint(
            "status IN ("
            "'created', 'confirmed', 'in_progress', "
            "'completed', 'cancelled', 'refunded', 'failed')",
            name=op.f("ck_orders_status"),
        ),
        sa.CheckConstraint("total_price > 0", name=op.f("ck_orders_total_price_positive")),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_orders_user_id_users"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
    )
    op.create_index("idx_orders_status", "orders", ["status"], unique=False)
    op.create_index("idx_orders_user_id", "orders", ["user_id"], unique=False)
    op.create_table(
        "order_delivery_info",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("recipient_name", sa.String(length=255), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("address", sa.Text(), nullable=False),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("postal_code", sa.String(length=20), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("shipped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_order_delivery_info_order_id_orders"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_delivery_info")),
        sa.UniqueConstraint("order_id", name=op.f("uq_order_delivery_info_order_id")),
    )
    op.create_index("idx_order_delivery_info_city", "order_delivery_info", ["city"], unique=False)
    op.create_table(
        "order_pickup_info",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("point_id", sa.UUID(), nullable=False),
        sa.Column("pickup_code", sa.CHAR(length=6), nullable=False),
        sa.Column("pickup_deadline", sa.DateTime(timezone=True), nullable=False),
        sa.Column("picked_up_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_order_pickup_info_order_id_orders"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["point_id"],
            ["points.id"],
            name=op.f("fk_order_pickup_info_point_id_points"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_pickup_info")),
        sa.UniqueConstraint("order_id", name=op.f("uq_order_pickup_info_order_id")),
        sa.UniqueConstraint("pickup_code", name=op.f("uq_order_pickup_info_pickup_code")),
    )
    op.create_index(
        "idx_order_pickup_info_pickup_deadline",
        "order_pickup_info",
        ["pickup_deadline"],
        unique=False,
    )
    op.create_index(
        "idx_order_pickup_info_point_id", "order_pickup_info", ["point_id"], unique=False
    )
    op.create_table(
        "order_products",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("product_name", sa.String(length=255), nullable=False),
        sa.Column("product_price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("grind", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "grind IS NULL OR grind IN ("
            "'extra_coarse', 'coarse', 'medium_coarse', 'medium', "
            "'medium_fine', 'fine', 'extra_fine')",
            name=op.f("ck_order_products_grind"),
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_order_products_quantity_positive")),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_order_products_order_id_orders"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_order_products_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_products")),
    )
    op.create_index("idx_order_products_order_id", "order_products", ["order_id"], unique=False)
    op.create_index("idx_order_products_product_id", "order_products", ["product_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_order_products_product_id", table_name="order_products")
    op.drop_index("idx_order_products_order_id", table_name="order_products")
    op.drop_table("order_products")
    op.drop_index("idx_order_pickup_info_point_id", table_name="order_pickup_info")
    op.drop_index("idx_order_pickup_info_pickup_deadline", table_name="order_pickup_info")
    op.drop_table("order_pickup_info")
    op.drop_index("idx_order_delivery_info_city", table_name="order_delivery_info")
    op.drop_table("order_delivery_info")
    op.drop_index("idx_orders_user_id", table_name="orders")
    op.drop_index("idx_orders_status", table_name="orders")
    op.drop_table("orders")
    op.drop_index("idx_points_type", table_name="points")
    op.drop_index("idx_points_name", table_name="points")
    op.drop_index("idx_points_is_active", table_name="points")
    op.drop_table("points")
    # ### end Alembic commands ###
