"""create ratings tables

Revision ID: e38361f22261
Revises: 1a202060566b
Create Date: 2026-05-27 07:04:57.910884+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e38361f22261"
down_revision: str | Sequence[str] | None = "1a202060566b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product_ratings",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("average_rating", sa.Numeric(precision=2, scale=1), nullable=False),
        sa.Column("total_ratings", sa.Integer(), nullable=False),
        sa.Column("distribution", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "average_rating BETWEEN 1.0 AND 5.0", name=op.f("ck_product_ratings_average_range")
        ),
        sa.CheckConstraint("total_ratings >= 1", name=op.f("ck_product_ratings_total_positive")),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_product_ratings_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_ratings")),
        sa.UniqueConstraint("product_id", name=op.f("uq_product_ratings_product_id")),
    )
    op.create_index(
        "idx_product_ratings_average", "product_ratings", ["average_rating"], unique=False
    )
    op.create_table(
        "ratings",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("rating", sa.SmallInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("rating BETWEEN 1 AND 5", name=op.f("ck_ratings_rating_scale")),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_ratings_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_ratings_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ratings")),
        sa.UniqueConstraint("product_id", "user_id", name=op.f("uq_ratings_product_id")),
    )
    op.create_index("idx_ratings_product_id", "ratings", ["product_id"], unique=False)
    op.create_index("idx_ratings_user_id", "ratings", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_ratings_user_id", table_name="ratings")
    op.drop_index("idx_ratings_product_id", table_name="ratings")
    op.drop_table("ratings")
    op.drop_index("idx_product_ratings_average", table_name="product_ratings")
    op.drop_table("product_ratings")
    # ### end Alembic commands ###
